name: tests
on:
  push:
    branches:
      - master
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: bayareawebpro/laravel-docker
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Composer dependencies
        run: |
          cd ./src
          composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Prepare Laravel Application
        run: |
          cd ./src
          cp .env.example .env
          php artisan key:generate
      - name: Run Testsuite
        run: |
          cd ./src
          vendor/bin/phpunit